# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 1d38c2f411c41d2a2dd829c3ba09ff4856e0adc39ebd7978f3cd4a0a784dbbfb722133829bd9fa9aa5f9dc9861f9270a73c14fff2feb8d8691088d1eb2b70045

test:
  secret_key_base: 1478bf9db59dc34b9c928c0255494fc27da7c9db45978cd1fe5390c072a621bcbec6aeff65493db27dc0323d312f57cb2f6c8bf30a0ae56d28e03581436b9b6e

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
